### ISSUE TITLE
320kbps versions?

### ISSUE THREAD

**Issue by Nik736** [ravishi/rdio-dl#7]
Hi there,

thanks for this script, even though the description says it might not work, it still works perfectly fine!! But it only downloads the 192kbps versions. Is there any way to make this work so it downloads the 320kbps versions of the songs? Is there any chance to get tracks with metadata?

I found type='mp3-high' in the source code but what would be the equivalent for the 320kbps version? And how would I get the AAC version?

Thanks for any suggestion or help!

Cheers
Nik

**Comment by ravishi** [comment]
Hey, there! I'm glad to hear it still works!

I believe you could try to tweak the parameters of the track request. You could find the proper `type` value by inspecting the calls made by the rdio.com player. Since we're basically emulating that player here, it is expected that everything that is possible to retrieve thought the player should also work here. 

And yes, it's possible to fill the Metadata automatically. I was hoping to use eyeD3 to do that, but had some trouble while interfacing with youtube-dl. This interface has been improved in recent ydl versions, so it should be possible now. You can check the `embed-ydl` branch in this repo where I updated this interface, but couldnt confirm if it's working or not.
